const tarotCards = [
  // Büyük Arkana (22 Kart)
  { id: 1, name: "Deli", meaning: "Başlangıç, özgürlük", description: "Yeni maceralar, risk alma ve sınırsız potansiyel." },
  { id: 2, name: "Büyücü", meaning: "Güç, yaratıcılık", description: "Kendini gerçekleştirme ve yetenekleri kullanma." },
  { id: 3, name: "Başrahibe", meaning: "Sezgi, bilinçaltı", description: "İç bilgi ve sırlarla bağlantı kurma." },
  { id: 4, name: "İmparatoriçe", meaning: "Bolluk, doğurganlık", description: "Yaratıcılık, sevgi ve doğa ile uyum." },
  { id: 5, name: "İmparator", meaning: "Otorite, güvenlik", description: "Disiplin, güç ve liderlik." },
  { id: 6, name: "Başrahip", meaning: "Maneviyat, gelenek", description: "Toplumsal kurallar ve spiritüel rehberlik." },
  { id: 7, name: "Aşıklar", meaning: "İlişkiler, karar", description: "Aşk, bağlılık ve hayat seçimleri." },
  { id: 8, name: "Savaş Arabası", meaning: "Zafer, kontrol", description: "Zorlukların üstesinden gelme ve başarı." },
  { id: 9, name: "Güç", meaning: "Cesaret, sabır", description: "İçsel güç ve şefkatle yaklaşmak." },
  { id: 10, name: "Ermiş", meaning: "İçe dönüş, yalnızlık", description: "Kendini keşfetme ve içsel rehberlik." },
  { id: 11, name: "Kader Çarkı", meaning: "Kader, değişim", description: "Hayatın döngüsü, talih değişimleri." },
  { id: 12, name: "Adalet", meaning: "Denge, dürüstlük", description: "Sorumluluk alma, etik davranış." },
  { id: 13, name: "Asılmış Adam", meaning: "Teslimiyet, farkındalık", description: "Fedakârlık ve olaylara farklı açıdan bakmak." },
  { id: 14, name: "Ölüm", meaning: "Dönüşüm, yenilenme", description: "Eskiyi bırakıp yeniye geçmek." },
  { id: 15, name: "Denge", meaning: "Uyum, sabır", description: "Ilımlılık, içsel denge." },
  { id: 16, name: "Şeytan", meaning: "Bağımlılık, arzular", description: "Kendini sınırlayan düşünceler." },
  { id: 17, name: "Kule", meaning: "Yıkım, ani değişim", description: "Ani farkındalıklar ve yıkıcı dönüşümler." },
  { id: 18, name: "Yıldız", meaning: "Umut, ilham", description: "İyileşme ve pozitif enerji." },
  { id: 19, name: "Ay", meaning: "Yanılsama, belirsizlik", description: "Bilinçaltı korkular ve kararsızlık." },
  { id: 20, name: "Güneş", meaning: "Mutluluk, başarı", description: "Pozitiflik, neşe ve açık iletişim." },
  { id: 21, name: "Mahkeme", meaning: "Uyanış, iç hesaplaşma", description: "Kendini değerlendirme ve yenilenme." },
  { id: 22, name: "Dünya", meaning: "Tamamlanma, başarı", description: "Bir döngünün sonu ve bütünlük." },

  // Küçük Arkana - Kupa Serisi
  { id: 23, name: "Kupa Ası", meaning: "Duygusal başlangıç", description: "Yeni ilişkiler, sevgi ve sezgisel gelişim." },
  { id: 24, name: "Kupa İkilisi", meaning: "Ortaklık, bağ", description: "Aşk ya da ruh eşi bağlantısı." },
  { id: 25, name: "Kupa Üçlüsü", meaning: "Kutlama, dostluk", description: "Sosyalleşme, mutluluk ve birliktelik." },
  { id: 26, name: "Kupa Dörtlüsü", meaning: "İçe çekilme, tatminsizlik", description: "Fırsatları fark edememe." },
  { id: 27, name: "Kupa Beşlisi", meaning: "Kayıp, üzüntü", description: "Hayal kırıklığı, geçmişe odaklanma." },
  { id: 28, name: "Kupa Altılısı", meaning: "Nostalji, geçmiş", description: "Anılara dalmak ve eski dostluklar." },
  { id: 29, name: "Kupa Yedilisi", meaning: "Kararsızlık, hayal", description: "Seçenekler arasında kaybolmak." },
  { id: 30, name: "Kupa Sekizlisi", meaning: "Terk etmek", description: "Duygusal olarak tatmin etmeyen şeyleri bırakmak." },
  { id: 31, name: "Kupa Dokuzlusu", meaning: "Dilek gerçekleşmesi", description: "Kişisel tatmin ve mutluluk." },
  { id: 32, name: "Kupa Onlusu", meaning: "Ailevi mutluluk", description: "Tam anlamıyla duygusal tatmin." },
  { id: 33, name: "Kupa Prensi", meaning: "Romantizm", description: "Yeni romantik teklifler, hayal gücü." },
  { id: 34, name: "Kupa Şövalyesi", meaning: "İdealist aşk", description: "Romantik bir teklif." },
  { id: 35, name: "Kupa Kraliçesi", meaning: "Şefkat, sezgi", description: "Empati ve duygusal denge." },
  { id: 36, name: "Kupa Kralı", meaning: "Olgun sevgi", description: "Duygusal liderlik ve denge." },

  // Küçük Arkana - Tılsım Serisi
  { id: 37, name: "Tılsım Ası", meaning: "Maddi fırsat", description: "Yeni iş ya da finansal gelişme." },
  { id: 38, name: "Tılsım İkilisi", meaning: "Denge, esneklik", description: "Çoklu görevler, denge kurmak." },
  { id: 39, name: "Tılsım Üçlüsü", meaning: "İş birliği", description: "Ekip çalışması, beceri gelişimi." },
  { id: 40, name: "Tılsım Dörtlüsü", meaning: "Tutunma, sahiplenme", description: "Güvenlik ihtiyacı." },
  { id: 41, name: "Tılsım Beşlisi", meaning: "Maddi zorluk", description: "Yoksunluk ve dışlanma hissi." },
  { id: 42, name: "Tılsım Altılısı", meaning: "Yardım, denge", description: "Vermek ve almak arasında denge." },
  { id: 43, name: "Tılsım Yedilisi", meaning: "Sabır, değerlendirme", description: "Zamanla gelişecek şeylere odaklanma." },
  { id: 44, name: "Tılsım Sekizlisi", meaning: "Çalışkanlık", description: "Yetenek geliştirme ve çaba." },
  { id: 45, name: "Tılsım Dokuzlusu", meaning: "Bağımsızlık", description: "Maddi bolluk ve kişisel başarı." },
  { id: 46, name: "Tılsım Onlusu", meaning: "Miras, aile bolluğu", description: "Uzun vadeli güvenlik." },
  { id: 47, name: "Tılsım Prensi", meaning: "Pratik adım", description: "İstikrarlı ve güvenilir başlangıçlar." },
  { id: 48, name: "Tılsım Şövalyesi", meaning: "Sorumluluk", description: "İş ve görevlerde kararlılık." },
  { id: 49, name: "Tılsım Kraliçesi", meaning: "Besleyicilik", description: "Pratik zekâ ve üretkenlik." },
  { id: 50, name: "Tılsım Kralı", meaning: "Maddi liderlik", description: "Finansal başarı ve yönetim." },

  // Küçük Arkana - Kılıç Serisi
  { id: 51, name: "Kılıç Ası", meaning: "Gerçek, fikir", description: "Yeni bir zihinsel başlangıç." },
  { id: 52, name: "Kılıç İkilisi", meaning: "Kararsızlık", description: "Zihinsel çatışma ve karar ihtiyacı." },
  { id: 53, name: "Kılıç Üçlüsü", meaning: "Kalp kırıklığı", description: "Acı, ihanet, kayıp." },
  { id: 54, name: "Kılıç Dörtlüsü", meaning: "Dinlenme", description: "Zihinsel mola ve iyileşme." },
  { id: 55, name: "Kılıç Beşlisi", meaning: "Çatışma", description: "Sert kazanımlar ve gurur." },
  { id: 56, name: "Kılıç Altılısı", meaning: "Geçiş", description: "Sıkıntılı bir dönemden çıkış." },
  { id: 57, name: "Kılıç Yedilisi", meaning: "Hile", description: "Gizli işler ve kaçış." },
  { id: 58, name: "Kılıç Sekizlisi", meaning: "Kısıtlanmışlık", description: "Kendi zihninle sınırlanmak." },
  { id: 59, name: "Kılıç Dokuzlusu", meaning: "Endişe", description: "Uykusuzluk, pişmanlık, stres." },
  { id: 60, name: "Kılıç Onlusu", meaning: "Son, ihanet", description: "Acı dolu bir son ve yenilenme." },
  { id: 61, name: "Kılıç Prensi", meaning: "Merak, uyanış", description: "Yeni fikirler ve dürtüler." },
  { id: 62, name: "Kılıç Şövalyesi", meaning: "Cesaretli hamle", description: "Hızlı ve kararlı hareket." },
  { id: 63, name: "Kılıç Kraliçesi", meaning: "Keskin zihin", description: "Gerçekle yüzleşme ve bağımsızlık." },
  { id: 64, name: "Kılıç Kralı", meaning: "Zihinsel liderlik", description: "Adaletli ve analitik kararlar." },

  // Küçük Arkana - Değnek Serisi
  { id: 65, name: "Değnek Ası", meaning: "Yeni fikir, ilham", description: "Yaratıcı potansiyelin patlaması." },
  { id: 66, name: "Değnek İkilisi", meaning: "Planlama", description: "Karar verme ve gelecek vizyonu." },
  { id: 67, name: "Değnek Üçlüsü", meaning: "Genişleme", description: "Fırsatlara açık olma." },
  { id: 68, name: "Değnek Dörtlüsü", meaning: "Kutlama", description: "Ev, aile ve toplulukla mutluluk." },
  { id: 69, name: "Değnek Beşlisi", meaning: "Rekabet", description: "Fikir çatışmaları." },
  { id: 70, name: "Değnek Altılısı", meaning: "Zafer", description: "Toplumsal takdir." },
  { id: 71, name: "Değnek Yedilisi", meaning: "Savunma", description: "Kendini ve fikirlerini koruma." },
  { id: 72, name: "Değnek Sekizlisi", meaning: "Hızlı gelişme", description: "İlerleme ve haberleşme." },
  { id: 73, name: "Değnek Dokuzlusu", meaning: "Dayanıklılık", description: "Yorgun ama dirençli olmak." },
  { id: 74, name: "Değnek Onlusu", meaning: "Yük", description: "Aşırı sorumluluk alma." },
  { id: 75, name: "Değnek Prensi", meaning: "Maceraperestlik", description: "Yaratıcı yolculuk." },
  { id: 76, name: "Değnek Şövalyesi", meaning: "Enerji, tutku", description: "Atılganlık ve heves." },
  { id: 77, name: "Değnek Kraliçesi", meaning: "Kendine güven", description: "Cezbedici, güçlü liderlik." },
  { id: 78, name: "Değnek Kralı", meaning: "Vizyon sahibi", description: "Yüksek hedefler ve ilham vericilik." }
];

export default tarotCards;
